version: '3'

services:
  data-integration:
    build: ./data_integration
    volumes:
      - ./data_integration:/usr/src/app
    ports:
      - 82:80
    restart: on-failure
      
  data-processing:
    build: ./data_processing
    volumes:
      - ./data_processing:/usr/src/app
    ports:
      - 81:80
    depends_on:
      - data-integration
    restart: on-failure

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 80:80
    depends_on:
      - data-processing
    restart: on-failure
