version: '3'

services:
  data-integration:
    build: ./data_integration
    volumes:
      - ./data_integration:/usr/src/app
    ports:
      - 5001:80
      
  data-processing:
    build: ./data_integration
    volumes:
      - ./data_integration:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - data-integration

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - data-processing
